[FRONTEND] Support `else if` in `@cond`
PennyLaneAI/catalyst pull request #104
Opened 2023-04-26 21:30 UTC by pengmai

**Context:** Supporting multiple branches with an `else-if`-like construct requires nesting `@cond` decorators with the user, which hurts readability.

**Description of the Change:** Add an `else_if` function directly to the front end.

**Benefits:** It is more ergonomic and readable to express programs with the desired branching functionality.

**Possible Drawbacks:** If the text formats of the JAXPRs are important, the use of a list to store the `branch_jaxprs` appears to mess with the variable naming with the inner branch functions. See how the function parameters in [frontend/test/pytest/test_conditionals.py](https://github.com/PennyLaneAI/catalyst/compare/main...pengmai:catalyst:multi-branch-cond?expand=1#diff-e8244850c25e67f887baf50586519acbbe13ffdfa432097adb8ffe3efda5282d) name their parameters "a" and "b" instead of continuing to use subsequent letters from the outside scope.

It's also possible, given my relative inexperience with JAX, that the variable name here is due to some misconfiguration.

**Related GitHub Issues:** #95

2023-04-26 23:11 UTC, dime10 commented
Hi @pengmai, thank you for submitting your pull request!

> Can anyone shed insight on why CodeFactor is highlighting issues around redefining functions and missing docstrings in the unit test file? It seems to me that the existing tests have those same "issues".

Indeed the test suite does not yet satisfy CodeFactor requirements (which was introduced later), and it is slowly being updated to match those standards. However, all new contributions must match the coding standards recommended by CodeFactor. Hope this answers your question :)

2023-04-27 13:37 UTC, dime10 commented
> Possible Drawbacks: If the text formats of the JAXPRs are important, the use of a list to store the branch_jaxprs appears to mess with the variable naming with the inner branch functions. See how the function parameters in [frontend/test/pytest/test_conditionals.py](https://github.com/PennyLaneAI/catalyst/compare/main...pengmai:catalyst:multi-branch-cond?expand=1#diff-e8244850c25e67f887baf50586519acbbe13ffdfa432097adb8ffe3efda5282d) name their parameters "a" and "b" instead of continuing to use subsequent letters from the outside scope.

This is an interesting observation, but likely just a quirk of the printer. I've noticed before that printing operations of the same jaxpr one at a time for example will restart the lettering at `a` for each of them.
Additionally, values from an outside scope accessed in the inner scope are present as arguments of the nested jaxpr, which to me would indicate that each jaxpr can be treated independently and does not rely on outside context, so I wouldn't be too worried about it.

2023-04-27 13:45 UTC, dime10 commented
> The "function redefined" issue on CodeFactor feels a little strange in the context of PennyLane programs in case a user wanted to name the different branch functions the same thing to conceptually group them (and indeed, one of the existing @cond unit tests explicitly tests this). I've nonetheless chosen different names within my new tests to pass CodeFactor for now.

Ah, I fully agree with you here, in fact this is also the style we show in the documentation :) 
We can just keep your version that you already have, but I would also be happy to add a Pylint exception for those test cases.

2023-04-27 18:15 UTC, dime10 requested changes
Amazing work @pengmai 🎉 🚀 🎉 Thank you for this contribution!

I have not much to say at all besides the few comments below. I'll enable the CI checks to run on your branch :)

2023-04-27 18:15 UTC, dime10 commented on frontend/catalyst/pennylane_extensions.py
> +    means that each execution path, a 'if' branch, any 'else if' branches, and a final 'otherwise'
```suggestion
    means that each execution path, an 'if' branch, any 'else if' branches, and a final 'otherwise'
```

2023-04-27 18:15 UTC, dime10 commented on frontend/test/pytest/test_conditionals.py
> +        @qjit()
Very minor, and I know some tests do specify the parenthesis, but they aren't needed unless arguments are supplied to `qjit`, so this is cleaner:
```suggestion
        @qjit
```

2023-04-27 18:19 UTC, dime10 commented
If you wouldn't mind adding your name and a short description of you changes to the [changelog](https://github.com/PennyLaneAI/catalyst/blob/main/doc/changelog.md), under `New features`, and with a link back to this PR, that would great!

2023-04-27 20:09 UTC, dime10 commented on frontend/catalyst/pennylane_extensions.py
> +            if expected != jaxpr.out_avals[:-1]:
Ah you're right, the variable names make that a bit confusing but the last branch is indeed included in this context 👍

2023-04-27 20:29 UTC, pengmai commented on frontend/catalyst/pennylane_extensions.py
> +            tuple(self.branch_fns) + (self.otherwise_fn,), args_tree, args_avals, "cond"
Nice, I'm a fan of this 👍

2023-04-27 20:56 UTC, dime10 commented on frontend/catalyst/pennylane_extensions.py
> +                )
Just looks like your missing a test for this exception :)

2023-04-27 21:52 UTC, dime10 approved these changes
Looking fantastic 💯

2023-04-27 21:53 UTC, merged