Apply clang-tidy to lightning.qubit runtime
PennyLaneAI/catalyst pull request #1261
Opened 2024-10-31 20:13 UTC by paul0403

**Context:**
Catalyst should start conforming to `clang-tidy`. As a first step, we apply it to the files in the lightning runtime.

**Description of the Change:**
Apply clang-tidy to lightning.qubit runtime. 
The target files are those in `runtime/lib/backend/lightning/lightning_dynamic`.

**Benefits:**
Better adherence to clang rules.

2024-10-31 20:36 UTC, rauletorresc requested changes
1. Nice work, these files needed to be refactored because Lightning will be fetching the main branch at the moment. However, these very same files will be deleted once the LQ plugin is removed from Catalyst, so this effort will be lost.
2. Do not forget to refactor the following headers as well, as they are fetched by Lightning:

- runtime/lib/backend/common/CacheManager.hpp
- runtime/lib/backend/common/QubitManager.hpp
- runtime/lib/backend/common/Utils.hpp
- runtime/include/Exception.hpp
- runtime/include/QuantumDevice.hpp
- runtime/include/RuntimeCAPI.h
- runtime/include/Types.h

2024-10-31 20:43 UTC, paul0403 commented
> 1. Nice work, these files needed to be refactored because Lightning will be fetching the main branch at the moment. However, these very same files will be deleted once the LQ plugin is removed from Catalyst, so this effort will be lost.

I envision the following workflow:
1. This PR, fixing [all errors in lightning's warnings-as-errors](https://github.com/PennyLaneAI/pennylane-lightning/actions/runs/11609135273/job/32325785221?pr=960), gets merged to catalyst main. At this point, catalyst main has both the common files (like the common/Utils.hpp) and the lightning qubit files, all passing clang tidy.
2. Lightning PR https://github.com/PennyLaneAI/pennylane-lightning/pull/960 fetches catalyst main, and their CI's clang tidy no longer sees errors on the common files. For the lightning files, at this point I guess you would need to manually "cherry-pick" the changes here into your lightning PR (since they are in different repositories)?
3. Lightning merges their PR. From lightning's perspective, everything is done. They see common files by fetching catalyst's, and see lightning files in their own repo.
4. Catalyst merges PR and removes lightning files.

Thoughts?

2024-10-31 21:10 UTC, rauletorresc commented
> > 1. Nice work, these files needed to be refactored because Lightning will be fetching the main branch at the moment. However, these very same files will be deleted once the LQ plugin is removed from Catalyst, so this effort will be lost.
> 
> I envision the following workflow:
> 
> 1. This PR, fixing [all errors in lightning's warnings-as-errors](https://github.com/PennyLaneAI/pennylane-lightning/actions/runs/11609135273/job/32325785221?pr=960), gets merged to catalyst main. At this point, catalyst main has both the common files (like the common/Utils.hpp) and the lightning qubit files, all passing clang tidy.
> 2. Lightning PR [Downstream LightningSimulator C++ API to the pennylane-lightning repository pennylane-lightning#960](https://github.com/PennyLaneAI/pennylane-lightning/pull/960) fetches catalyst main, and their CI's clang tidy no longer sees errors on the common files. For the lightning files, at this point I guess you would need to manually "cherry-pick" the changes here into your lightning PR (since they are in different repositories)?
> 3. Lightning merges their PR. From lightning's perspective, everything is done. They see common files by fetching catalyst's, and see lightning files in their own repo.
> 4. Catalyst merges PR and removes lightning files.
> 
> Thoughts?

I was wrong, the effort is not lost, cause I will update the LQ plugin in Lightning with your changes. Thanks for clarifying that.

The workflow you envision seems correct to me, yes.

2024-11-01 15:29 UTC, paul0403 commented on runtime/CMakeLists.txt
> +option(RUNTIME_CLANG_TIDY "Enable Clang Tidy" ON)
disable CI clang tidy before merging

2024-11-01 15:29 UTC, paul0403 commented on runtime/Makefile
> +		-DCLANG_TIDY_BINARY=clang-tidy \
disable CI clang tidy before merging

2024-11-01 15:29 UTC, paul0403 commented on runtime/Makefile
> +		-DCLANG_TIDY_BINARY=clang-tidy \
disable CI clang tidy before merging

2024-11-01 15:39 UTC, paul0403 commented on runtime/Makefile
> +ENABLE_OPENQASM?=OFF
turn this back on when merging

2024-11-01 17:17 UTC, paul0403 commented
@rauletorresc So I think this is ready to go. In the past couple of commits, I did the following:
1. https://github.com/PennyLaneAI/catalyst/pull/1261/commits/b38c9a8e120e7471b634280f3c2d64c0f5fdd87c update `runtime/.clang-tidy` to the same configs as [the `.clang-tidy` in lightning repository ](https://github.com/PennyLaneAI/pennylane-lightning/blob/master/pennylane_lightning/.clang-tidy)
2. https://github.com/PennyLaneAI/catalyst/pull/1261/commits/722621eb92d1bda54db64d1490a096753510240d enable `clang-tidy` warnings as errors in catalyst runtime builds
3. https://github.com/PennyLaneAI/catalyst/pull/1261/commits/1e82397e88cc2970ea48bee9dd335897342461ba Skip openqasm backend builds in CI, since we are only tidying lightning runtime here, so that we don't block ourselves with the warnings-as-errors from openqasm backend
4. Apply clang tidy suggestions

This is the status of https://github.com/PennyLaneAI/catalyst/pull/1261/commits/690e3dcfd1d1e0637b2dd550b0ac8e287d2bf965. At this point, CI will build lightning runtime, with clang-tidy enabled, and not build openqasm. Runtime builds (with warnings as errors enabled) and tests all succeed. All failing frontend tests are because openqasm backend is not built.

At this point, all the lightning files should be clang-tidy-ed, according to lightning repo's clang tidy config.

If we are good with this, I will:
1. Turn off clang-tidy in catalyst CI
2. Turn back on openqasm builds in catalyst CI
since catalyst repo as a whole is not ready for clang-tidy yet.

cc @mlxd

2024-11-01 18:12 UTC, rauletorresc approved these changes
LGTM

2024-11-01 18:25 UTC, merged