Remove shots attr from `expval` and `var` operations
PennyLaneAI/catalyst pull request #1360
Opened 2024-12-05 21:50 UTC by paul0403

**Context:**
As part of the work to support dynamically shaped measurement primitives, shots is now tied to the device through a SSA value, so it can be dynamic. See #1310 .

Correspondingly, the static shots int literal attribute of the `expval` and `var` operations in mlir should be removed. This is more so the case since their shots values are not actually used in their respective runtime CAPIs.

**Description of the Change:**
Remove shots attr from `expval` and `var` operations in mlir, and frontend tracing and jax primitives.

**Benefits:**
Unification of how measurement operations handle shots.

[sc-78845]

2024-12-05 21:50 UTC, paul0403 commented on mlir/include/Quantum/IR/QuantumOps.td
> +        //OptionalAttr<I64Attr>:$shots
do `var`

2024-12-05 21:50 UTC, paul0403 commented on frontend/catalyst/jax_primitives.py
> +def _expval_abstract_eval(obs, shape=None):
changelog

2024-12-05 21:52 UTC, paul0403 commented
@rauletorresc was this the "some measurements in c++ doesn't actually use shots" you were talking about a while ago?

2024-12-06 20:05 UTC, erick-xanadu approved these changes

2024-12-06 20:06 UTC, erick-xanadu requested changes

2024-12-06 20:06 UTC, erick-xanadu commented on frontend/catalyst/from_plxpr.py
> +            mval = expval_p.bind(obs, shape=shaped_array.shape)
Should you also bind to var_p?

2024-12-06 20:08 UTC, paul0403 commented on frontend/catalyst/from_plxpr.py
> +            mval = expval_p.bind(obs, shape=shaped_array.shape)
done

2024-12-06 20:36 UTC, erick-xanadu approved these changes

2024-12-06 20:40 UTC, merged