Add changelog reminder action
PennyLaneAI/catalyst pull request #32
Opened 2023-03-02 22:56 UTC by josh146

**Context:** Now that we are working on v0.2.0, having a changelog reminder will help us avoid additional work during the release, by ensuring all changes are documented in PRs :)

**Description of the Change:** Adds an action to remind us to edit the changelog if we haven't already.

**Benefits:** As above!

**Possible Drawbacks:** n/a

**Related GitHub Issues:** n/a

2023-03-02 22:58 UTC, josh146 commented
Note: I'm not going to add a changelog reminder in this PR since I am adding a repo action, and not touching the actual catalyst package :)

2023-03-02 23:12 UTC, josh146 commented
> However, you can't have a changelog entry, with reference to the correct PR, before opening said PR. Is there any way to resolve this?

Yep it's a chicken-or-egg situation. On PL typically we add the changelog entry to our branch first, and once the PR is open edit in the PR number.

2023-03-02 23:15 UTC, dime10 commented
> Yep it's a chicken-or-egg situation. On PL typically we add the changelog entry to our branch first, and once the PR is open edit in the PR number.

That's unfortunate, easy to forget adding the PR number for both the author and reviewer 😞

2023-03-02 23:18 UTC, josh146 commented
Yep. We haven't come up with a better solution (there might be one?) but the reminder has been incredibly helpful. It is _very_ easy to forget to update the changelog at all

2023-03-03 14:13 UTC, maliasadi approved these changes
LGTM :100:

2023-03-06 16:23 UTC, dime10 requested changes

2023-03-06 16:23 UTC, dime10 commented on .github/workflows/changelog_reminder.yaml
> +    types: [opened, ready_for_review]
How about running the reminder once a review is being submitted?
```suggestion
  pull_request_review:
    types: [submitted]
```

2023-03-06 16:50 UTC, dime10 approved these changes

2023-03-06 18:36 UTC, merged