[Frontend] Eliminate python3.11 warnings
PennyLaneAI/catalyst pull request #527
Opened 2024-02-20 21:53 UTC by jay-selby

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new functions and code must be clearly commented and documented.

- [ ] Ensure that code is properly formatted by running `make format`.
      The latest version of black and `clang-format-14` are used in CI/CD to check formatting.

- [ ] All new features must include a unit test.
      Integration and frontend tests should be added to [`frontend/test`](../frontend/test/),
      Quantum dialect and MLIR tests should be added to [`mlir/test`](../mlir/test/), and
      Runtime tests should be added to [`runtime/tests`](../runtime/tests/).

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**
Clean up the warnings generated by the frontend tests.
Fixes: SC-48324

**Description of the Change:**

**Benefits:**
Reduce noise when running the test suite.  Discover issues that might exist in the code.

**Possible Drawbacks:**
Possibly trapping a warning instead of fixing the underlying cause.

2024-04-05 21:06 UTC, dime10 requested changes
Love to see the warnings eliminated 💯

2024-04-05 21:06 UTC, dime10 commented on frontend/test/pytest/test_config_functions.py
> +class DeviceTest(qml.QubitDevice):
`DeviceTest` does not make sense as a device name, it indicates the main object is a "test" not a "device".

2024-04-05 21:06 UTC, dime10 commented on frontend/test/pytest/test_jit_behaviour.py
> +    @pytest.mark.filterwarnings("ignore::pytest.PytestUnraisableExceptionWarning")
Should we look into resolving the root instead of silencing the warning?

2024-04-05 21:06 UTC, dime10 commented on frontend/test/pytest/test_jit_behaviour.py
> +        @qjit
Why remove this?

2024-04-30 18:39 UTC, erick-xanadu commented on frontend/catalyst/compiler.py
> +            raise CompileError("Requesting the output of an empty pipeline")
Have a suggestion? :)

2024-04-30 18:40 UTC, erick-xanadu commented on frontend/test/pytest/test_meta_ops.py
> +    result = qjit(qml.qnode(qml.device("lightning.qubit", wires=4), interface="jax")(circuit))()
https://github.com/PennyLaneAI/catalyst/pull/527/commits/e52f03a73b4dc333b19bd1fb2e1e92ec1856713a

2024-04-30 19:00 UTC, dime10 commented on frontend/catalyst/compiler.py
> +            raise CompileError("Requesting the output of an empty pipeline")
Something about invalid pass pipeline name no? Or is an "empty pipeline" something that can actually happen? If so we might want to split this into two checks and not make the default value `[]` when `pipeline` is not found.

2024-04-30 20:21 UTC, erick-xanadu commented on frontend/catalyst/compiler.py
> +            raise CompileError("Requesting the output of an empty pipeline")
How about this? https://github.com/PennyLaneAI/catalyst/pull/527/commits/7a59036715ae4e582e48a2aeadbd94c1c89c1e58

2024-04-30 20:39 UTC, dime10 commented on frontend/catalyst/compiler.py
> +            raise CompileError("Requesting the output of an empty pipeline")
Nice!

2024-04-30 20:40 UTC, dime10 approved these changes
🎉

2024-05-01 13:24 UTC, merged