Enable multi-threading compilation
PennyLaneAI/catalyst pull request #595
Opened 2024-03-08 18:54 UTC by erick-xanadu

**Context:** Multi-threading compilation was disabled in the past due to issues with how the IR was being printed.

**Description of the Change:** Re-enable multi threaded compilation. Remove dead code.

**Benefits:** Possibly better compile times.

**Related GitHub Issues:** Fixes #466

2024-03-11 18:15 UTC, dime10 commented
I think this might still cause the IR to be printed out of order since we handle printing via the special "tailMarker" pass, and if the passes run in parallel the printing could happen before other passes terminate.

Ideally we would also replace the `runAfterPass` call with the `runAfterPipeline` method before merging this PR :)
https://mlir.llvm.org/doxygen/classmlir_1_1PassInstrumentation.html#a195e695bcacbcae0ba69d95dae23d383
(it also has the added benefit that it will simplify the code)

2024-03-13 10:43 UTC, grwlf requested changes

2024-03-13 10:43 UTC, grwlf commented on mlir/lib/Driver/CompilerDriver.cpp
> -    // Let's try to enable multithreading. Do not forget to protect the printing.
There might be issues with file name counter, if I remeber it correctly. Could you please check?

2024-04-25 17:54 UTC, erick-xanadu commented
superseded by #655

2024-04-25 17:54 UTC, closed without merging