Relax device-spec observables validation
PennyLaneAI/catalyst pull request #629
Opened 2024-03-25 14:26 UTC by grwlf

**Context:** Quantum device config now contains only native observables (it means, handled by C-API), while the `device.observables` may contain additional non-native observables supported by the device Python API.

**Description of the Change:** By this PR we relax the observables validation.

**Benefits:** Fix support toml schema 2 configs.

**Possible Drawbacks:** 

**Related GitHub Issues:**
* https://github.com/PennyLaneAI/pennylane-lightning/pull/659
* https://github.com/PennyLaneAI/pennylane-lightning/pull/642

2024-03-25 16:09 UTC, erick-xanadu requested changes
Do you know if this interferes with lightning latest changes? I am thinking specifically about the migration to the new device API.

2024-03-25 17:04 UTC, grwlf commented
> Do you know if this interferes with lightning latest changes? I am thinking specifically about the migration to the new device API.

I don't know for sure, but most probably it does not. It is only related to how we interpret the information contained in the toml files.

2024-03-26 13:01 UTC, erick-xanadu commented
> I don't know for sure, I think that it does not. It is only related to how we interpret the information contained in the toml files.

Thanks Sergei! I ran the latest/latest action on this branch and it is no different than main/latest/latest. I agree that this might be independent of the new device API.

2024-04-01 17:17 UTC, erick-xanadu commented on frontend/catalyst/utils/runtime.py
> +        # device data superseeds the specification.
```suggestion
        # device data supercedes the specification.
```

2024-04-01 17:18 UTC, erick-xanadu approved these changes

2024-04-05 14:39 UTC, merged