[WIP] Fixing ```Batching rule for 'gather' not implemented``` for jax.scipy.linalg.expm under qml.qjit.
PennyLaneAI/catalyst pull request #733
Opened 2024-05-10 20:34 UTC by paul0403

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new functions and code must be clearly commented and documented.

- [ ] Ensure that code is properly formatted by running `make format`.
      The latest version of black and `clang-format-14` are used in CI/CD to check formatting.

- [ ] All new features must include a unit test.
      Integration and frontend tests should be added to [`frontend/test`](../frontend/test/),
      Quantum dialect and MLIR tests should be added to [`mlir/test`](../mlir/test/), and
      Runtime tests should be added to [`runtime/tests`](../runtime/tests/).

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:** closes #628

2024-05-10 20:47 UTC, paul0403 commented
self reminder to do changelog

2024-05-13 14:48 UTC, paul0403 commented
########## Description ###########
The root cause of this batching-rule-not-implemented error: the implemented batching rules are stored in the dictionary ```jax._src.interpreters.batching.primitive_batchers```, which is a dictionary of the form ```dict[jax._src.core.Primitive, BatchingRule]```.

To retrive the batching rules from the dictionary, jax source code does 
```python
  def get_primitive_batcher(self, primitive, frame):
    if primitive in primitive_batchers:
      return primitive_batchers[primitive]
    elif self.spmd_axis_name is not None and primitive in spmd_axis_primitive_batchers:
      return partial(spmd_axis_primitive_batchers[primitive],
                     self.spmd_axis_name, frame.size, frame.name,
                     frame.main_trace.trace_type)
    elif primitive in axis_primitive_batchers:
      return self.get_axis_primitive_batcher(primitive, frame)
    msg = "Batching rule for '{}' not implemented"
    raise NotImplementedError(msg.format(primitive))
```

... and raises the seen "batching rule not implemented" error when none of the three if conditions are met. 

This bug is not present if we just jit with jax:
```python
import jax
from jax import numpy as jnp

@jax.jit
def func(x):
	res = jax.scipy.linalg.expm(-2.0* x)
	return res

y = jnp.array( [[0.1, 0.2], [5.3, 1.2]] )
x = func(y)
print(x)
print(jax.make_jaxpr(func)(y))

>>> [[ 2.0767686  -0.23879547]
 [-6.328081    0.76339304]]

 let searchsorted = { lambda ; a:f32[2] b:f32[]. let
    _:i32[] c:i32[] = scan[
      jaxpr={ lambda ; d:f32[2] e:f32[] f:i32[] g:i32[]. let
          h:i32[] = add f g
          i:i32[] = pjit[
            name=floor_divide
            jaxpr={ lambda ; j:i32[] k:i32[]. let
                l:i32[] = convert_element_type[new_dtype=int32 weak_type=False] k
                m:i32[] = div j l
                n:i32[] = sign j
                ....
                ....

```

and from just jitting with jax, and some detective work, we can see that the first if block, 
```python
    if primitive in primitive_batchers:
      return primitive_batchers[primitive]
```
should trigger for expm. 


The primitive named ```"gather"``` in the jax source code is ```jax._src.lax.slicing.gather_p```, which is produced, and whose batching rule is added to the dictionary, by
```python
gather_p = standard_primitive(
    _gather_shape_rule, _gather_dtype_rule, 'gather',
    weak_type_rule=_argnum_weak_type(0))
batching.primitive_batchers[gather_p] = _gather_batching_rule
```

This dictionary key has a counterpart in catalyst source base called ```gather2_p``` in frontend/catalyst/jax_extras/tracing.py:
```python
...
from jax._src.interpreters.partial_eval import trace_to_jaxpr_dynamic2
from catalyst.jax_extras.patches import _gather_shape_rule_dynamic
...

def make_jaxpr2(
    fun: Callable,
    static_argnums: Any | None = None,
    abstracted_axes: Any | None = None,
) -> Callable[..., (tuple[ClosedJaxpr, PyTreeDef])]:
    """A customized version of ``jax.make_jaxpr``, compatible with the JAX dynamic API."""

    ...

    gather2_p = standard_primitive(
        _gather_shape_rule_dynamic,
        _gather_dtype_rule,
        "gather",
        weak_type_rule=_argnum_weak_type(0),
    )

    ...

    @wraps(fun)
    def make_jaxpr_f(*args, **kwargs):
        with Patcher(
            (jax._src.interpreters.partial_eval, "get_aval", get_aval2),
            (jax._src.lax.slicing, "gather_p", gather2_p),
        ), ExitStack():    
        ...
        jaxpr, output_type, consts = trace_to_jaxpr_dynamic2(f)
        ...
```

We have a custom ```gather``` primitive because we want a custon dynamic shape rule. 

Currently, the patcher has replaced the ```gather_p``` in the file ```jax._src.lax.slicing```, but has not replaced the actual batching rule dictionary, since the dictionary is in a different file! Therefore, the dictionary still has ```slicing.gather_p``` as key, not ```catalyst. ... .gather2_p```, which means ```if primitive in primitive_batchers:``` is not triggered.


As a fix, we make a copy of the batching rule dictionary, add this new key to this new dictionary, and patch the old batching rule dict with this new dict. See the code changed. 



############ Impact ################
- ```make test-frontend``` passes under this change. 
- Performance:

2024-05-13 18:29 UTC, paul0403 commented
As per @mlxd Lee's suggestion, a mini-benchmark was added to test if this change degrades performance in any way. 

This small mini-benchmark can also be added to the catalyst repo, if desired. 

```python
# A general catalyst workflow for mini-benchmarking performance
# The workflow is taken from 
# https://docs.pennylane.ai/projects/catalyst/en/latest/demos/qml/tutorial_qubit_rotation.html

import time
start = time.time()

#############
import pennylane as qml
from catalyst import qjit, grad
import jax.numpy as jnp

class task:
    def __call__(self):
        dev1 = qml.device("lightning.qubit", wires=1)

        @qml.qnode(device=dev1)
        def circuit(params):
            qml.RX(params[0], wires=0)
            qml.RY(params[1], wires=0)
            return qml.expval(qml.PauliZ(0))


        @qjit
        def jit_circuit(params):
            return circuit(params)

        #print(jit_circuit(jnp.array([0.54, 0.12])))


        jit_cost = qjit(circuit)
        jit_grad = qjit(grad(circuit))
        init_params = jnp.array([0.011, 0.012])
        #print(jit_cost(init_params))

        # set the number of steps
        steps = 100
        # set the initial parameter values
        params = init_params
        # step of the gradient descend
        stepsize = 0.4

        for i in range(steps):
            # update the circuit parameters
            dp = jit_grad(params)
            params = params - stepsize*dp

            #if (i + 1) % 5 == 0:
                #print("Cost after step {:5d}: {: .7f}".format(i + 1, jit_cost(params)))

        opt_1 = params
        #print("Optimized rotation angles: {}".format(opt_1))

run_task = task()
for i in range(100):
    run_task()
################

end = time.time()
print("Run time: ", end-start)
```

Without the change, run time is 
```>>> Run time:  15.234557390213013```

With the change, run time is 
```>>> Run time:  15.106917142868042```

So performance is not impacted. 

It might be a good idea to have such benchmarking suites that also check functionality (right now functionality is simply checked by uncommenting prints and comparing the results with those on the documentation page), have more mature workflows, etc., in the codebase.

2024-05-14 13:21 UTC, erick-xanadu requested changes
Awesome! Thank you. This looks correct, but a test is still missing. Can you add a test (even if we know expm will still fail with the other error). 

[You can use pytest.mark.xfail,](https://docs.pytest.org/en/latest/how-to/skipping.html) and once the other changes are in, change it back to success.

2024-05-14 17:16 UTC, erick-xanadu approved these changes
:1st_place_medal:

2024-05-14 17:23 UTC, merged