Have a documentation for accessing the original function of a QJIT object
PennyLaneAI/catalyst pull request #766
Opened 2024-05-27 20:05 UTC by paul0403

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new functions and code must be clearly commented and documented.

- [ ] Ensure that code is properly formatted by running `make format`.
      The latest version of black and `clang-format-14` are used in CI/CD to check formatting.

- [ ] All new features must include a unit test.
      Integration and frontend tests should be added to [`frontend/test`](../frontend/test/),
      Quantum dialect and MLIR tests should be added to [`mlir/test`](../mlir/test/), and
      Runtime tests should be added to [`runtime/tests`](../runtime/tests/).

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:** Some core PennyLane methods (e.g. `qml.matrix`) only take in QNodes, and support for passing compiled QJIT objects into them is not added yet. As a result, it should be included in the documentation that users can access the QNode of a compiled QJIT object through `QJIT.original_function`. 

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**
https://github.com/PennyLaneAI/catalyst/issues/765

2024-05-27 20:24 UTC, dime10 commented
This is nice. I'm also wondering if we could make the attribute show up in the API docs for the QJIT class:
https://docs.pennylane.ai/projects/catalyst/en/stable/code/api/catalyst.QJIT.html

2024-05-28 00:10 UTC, josh146 commented
@paul0403 we also in a few places in PL have hardcoded this in, for e.g., the `qml.draw` function:

https://github.com/PennyLaneAI/pennylane/blob/59a1e0586e707d057a0c92d4239036afa5312b73/pennylane/drawer/draw.py#L213-L214

It might be worth doing this for `qml.matrix` as well

2024-05-28 19:17 UTC, paul0403 commented
> @paul0403 we also in a few places in PL have hardcoded this in, for e.g., the `qml.draw` function:
> 
> https://github.com/PennyLaneAI/pennylane/blob/59a1e0586e707d057a0c92d4239036afa5312b73/pennylane/drawer/draw.py#L213-L214
> 
> It might be worth doing this for `qml.matrix` as well

Added this to the core repo: https://github.com/PennyLaneAI/pennylane/pull/5753

2024-05-30 17:03 UTC, dime10 requested changes
Thanks for improving the docs 💪

2024-05-30 18:14 UTC, paul0403 commented on doc/dev/sharp_bits.rst
> +ValueError: wire_order is required by qml.matrix() for quantum functions.
This is no longer accurate, I will remove

2024-05-30 18:45 UTC, paul0403 commented on doc/dev/sharp_bits.rst
> +Despite all the compatibility restrictions discussed above, if you really wish to access the QNode compiled by :func:`@qjit <~.qjit>` and pass them into various PennyLane methods, you can access them
I think I was trying to keep with the flow of the document from the previous sections discussing transforms and decompositions with Catalyst, but I think this new version is clearer.

2024-05-30 19:04 UTC, paul0403 commented on doc/dev/sharp_bits.rst
> +
added this note on `draw` and `matrix`

2024-05-30 21:11 UTC, dime10 approved these changes
Nice work 👍

2024-05-30 21:46 UTC, merged