[Runtime][WIP] Remove unnecessary copy
PennyLaneAI/catalyst pull request #91
Opened 2023-04-11 15:51 UTC by erick-xanadu

**Context:** The state was copied from a vector to another vector to a memref buffer. There was a redundant vector copy. For the following program:

```c
#include <stdio.h>
#include <stdlib.h>

struct MemRefDouble {
  double *allocated;
  double *aligned;
  int offset;
};

// complex<double> type
struct CplxT_double {
    double real;
    double imag;
};

typedef struct CplxT_double CplxT_double;

struct MemRefT_CplxT_double_1d {
    CplxT_double *data_allocated;
    CplxT_double *data_aligned;
    size_t offset;
    size_t sizes[1];
    size_t strides[1];
};

extern void __quantum__rt__finalize();
extern void __quantum__rt__initialize();

extern void* __quantum__rt__qubit_allocate_array(int);
extern void __quantum__qis__State(struct MemRefT_CplxT_double_1d *, int, ...);
extern void *_mlir_memref_to_llvm_alloc(size_t);

int
main(int argc, char** argv)
{
  double buffer[1] = {0.0};
  __quantum__rt__initialize();
  char* endptr = NULL;
  size_t num_qubits = strtol(argv[1], &endptr, 10);
  CplxT_double *buffer_result = (CplxT_double *) _mlir_memref_to_llvm_alloc(sizeof(struct CplxT_double) * 1U << num_qubits);
  struct MemRefT_CplxT_double_1d result;
  result.data_allocated = buffer_result;
  result.data_aligned = buffer_result;
  void* array = __quantum__rt__qubit_allocate_array(num_qubits);
  __quantum__qis__State(&result, 0);
  __quantum__rt__finalize();
}

```

running 

```
valgrind --tool=massif ./a.out 25
```

Shows a peak memory usage of 1.5 GB evenly distributed between three callsites

```
    GB
1.500^                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
     |                @                                                      #
     |                @                                                      #
     |                @                                                      #
     |                @                                                      #
     |                @                                                      #
     |                @                                                      #
     | @@@@@@@@@@@@@@@@                                                      #
     | @              @                                                      #
     | @              @                                                      #
     | @              @                                                      #
     | @              @                                                      #
     | @              @                                                      #
   0 +----------------------------------------------------------------------->Mi
     0                                                                   433.1

Number of snapshots: 75
 Detailed snapshots: [12, 14, 16, 24, 44, 45, 48, 50, 51, 53, 54, 55, 57, 58, 60, 62, 64, 68, 69, 70 (peak)]

```

```
--------------------------------------------------------------------------------
  n        time(i)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
 70    454,061,636    1,610,785,072    1,610,763,090        21,982            0
100.00% (1,610,763,090B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->33.33% (536,870,912B) 0x48F1D66: Catalyst::Runtime::Simulator::LightningSimulator::State() (in /home/eo/Code/catalyst-latest/runtime/build/lib/backend/librt_backend.so)
| ->33.33% (536,870,912B) 0x4A4388F: __quantum__qis__State (in /home/eo/Code/catalyst-latest/runtime/build/lib/capi/librt_capi.so)
|   ->33.33% (536,870,912B) 0x1093B8: main (a.c:45)
|     
->33.33% (536,870,912B) 0x48F66B9: std::vector<std::complex<double>, Pennylane::Util::AlignedAllocator<std::complex<double> > >::vector(unsigned long, std::complex<double> const&, Pennylane::Util::AlignedAllocator<std::complex<double> > const&) (in /home/eo/Code/catalyst-latest/runtime/build/lib/backend/librt_backend.so)
| ->33.33% (536,870,912B) 0x48F6593: Pennylane::StateVectorDynamicCPU<double>::StateVectorDynamicCPU(unsigned long, Pennylane::Threading, Pennylane::CPUMemoryModel) (in /home/eo/Code/catalyst-latest/runtime/build/lib/backend/librt_backend.so)
|   ->33.33% (536,870,912B) 0x48F04BA: Catalyst::Runtime::Simulator::LightningSimulator::AllocateQubits(unsigned long) (in /home/eo/Code/catalyst-latest/runtime/build/lib/backend/librt_backend.so)
|   | ->33.33% (536,870,912B) 0x4A3EB65: __quantum__rt__qubit_allocate_array (in /home/eo/Code/catalyst-latest/runtime/build/lib/capi/librt_capi.so)
|   |   ->33.33% (536,870,912B) 0x1093A7: main (a.c:44)
|   |     
|   ->00.00% (0B) in 1+ places, all below ms_print's threshold (01.00%)
|   
->33.33% (536,870,912B) 0x4A3E5CD: _mlir_memref_to_llvm_alloc (in /home/eo/Code/catalyst-latest/runtime/build/lib/capi/librt_capi.so)
| ->33.33% (536,870,912B) 0x109388: main (a.c:40)
|   
->00.01% (150,354B) in 1+ places, all below ms_print's threshold (01.00%)

```

The first callsite is the temporary vector used to pass results from PL-lightning library to the C-API runtime. The second callsite to the aligned allocator in PL-lightning. The third one is the memory requested in the main function to hold the result values.

**Description of the Change:** This is just a WIP to find other possible redundant copies. The changes involve passing the data pointer directly to the memref for copying. After this change, the same program shows the following memory profile:

```
    GB
1.000^                            ########################################### 
     |                            #                                           
     |                            #                                           
     |                            #                                           
     |                            #                                           
     |                            #                                           
     |                            #                                           
     |                            #                                           
     |                            #                                           
     |                            #                                           
     |  @@@@@@@@@@@@@@@@@@@@@@@@@@#                                          :
     |  @                         #                                          :
     |  @                         #                                          :
     |  @                         #                                          :
     |  @                         #                                          :
     |  @                         #                                          :
     |  @                         #                                          :
     |  @                         #                                          :
     |  @                         #                                          :
     |  @                         #                                          :
   0 +----------------------------------------------------------------------->Mi
     0                                                                   241.1
```

```
100.00% (1,073,892,930B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->49.99% (536,870,944B) 0x48F6619: std::vector<std::complex<double>, Pennylane::Util::AlignedAllocator<std::complex<double> > >::vector [...]

2023-04-11 18:21 UTC, maliasadi requested changes
I know that we already discussed this issue but have to mention again here that the main reason we ended up returning a deep-copy of the state vector instead of a reference (or pointer to the underlying data) was because of keeping the `State` method as general and static as possible. Note that every backend simulator has its own data-type for representing state-vectors. You can check on the implementation of Lightning-kokkos for example. How would you think this issue can be tackled?

2023-04-11 18:38 UTC, erick-xanadu commented
> I know that we already discussed this issue but have to mention again here that the main reason we ended up returning a deep-copy of the state vector instead of a reference (or pointer to the underlying data) was because of keeping the State method as general and static as possible. Note that every backend simulator has its own data-type for representing state-vectors. You can check on the implementation of Lightning-kokkos for example. How would you think this issue can be tackled?

The last message I received on the topic was that you liked the idea about getting rid of the copy. :sweat_smile: But yes, we can hold on to this. The way to get rid of it would be to have a per-device lowering, where we lower the QIR to the corresponding calls to the lightning API and the QIR calls to kokkos to the kokkos API.

2023-04-11 19:16 UTC, maliasadi commented
> The way to get rid of it would be to have a per-device lowering, where we lower the QIR to the corresponding calls to the lightning API and the QIR calls to kokkos to the kokkos API.

This is not going to happen soon ;)

2023-04-11 19:21 UTC, erick-xanadu commented
Ok, but we should note that there are inefficiencies introduced by this interface and once we get rid of this interface, it will unlock optimization opportunities.

2023-04-11 19:22 UTC, closed without merging

2023-04-12 19:40 UTC, erick-xanadu commented
> we all agree that one copy is necessary in order to leave the internal device state intact when a quantum state is returned to the user program

Yes

> the second copy here exists to allow the generic QuantumDevice interface to return a std::vector without making assumptions about which datatype the backend uses to store the statevector

Yes

> What if the QuantumDevice interface returns some kind of view of the data instead, without assuming it is a complex vector? Is the std::vector datatype, or the complex data type, or both, the issue? I guess getting a array view of arbitrary complex container is tricky, unless we return two views to the real and imaginary parts thus making no assumptions about how the complex data is stored?

Yes. A view would remove the copy. It complicates the API a bit. I would need a more concrete description of the view, but I can imagine something concretely as two iterators, one for the real part and the other for the complex part. Then there would be no copy of the data.

2023-04-12 21:44 UTC, dime10 commented
What if the QuantumDevice interface actually provides (accepts as argument) the iterator that the device implementation must write the data into?

Because I was also thinking that this must work for something like `probs` as well, not just `state`, and it would eliminate the copy in the runtime to move the data from the device provided buffer into the memref.